// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELBOW_H
#define ELBOW_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Elbow: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	std::shared_ptr<frc::SpeedController> elbowSpark;
	std::shared_ptr<frc::DigitalInput> elbowTopLimit;
	std::shared_ptr<frc::DigitalInput> elbowBottomLimit;

 public:
	Elbow();
	void InitDefaultCommand() override;
	void Periodic() override;
	void ElbowUp();
	void ElbowDown();
	void TakeJoy(double);
	void ElbowStop();
	double joyValue;
};

#endif
