// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "ElBrake.h"
#include "../RobotMap.h"

ElBrake::ElBrake() : frc::Subsystem("ElBrake") {
    elBrakeSolenoid = RobotMap::elBrakeElBrakeSolenoid;

 }

void ElBrake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
}

void ElBrake::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void ElBrake::BrakeOn(){
	elBrakeSolenoid->Set(frc::DoubleSolenoid::kReverse);
}
void ElBrake::BrakeOff(){
	elBrakeSolenoid->Set(frc::DoubleSolenoid::kForward);
}
void ElBrake::Stop(){
	elBrakeSolenoid->Set(frc::DoubleSolenoid::kOff);
}

