// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoPos2L2.h"
#include "Commands/LowerElbow.h"
#include "Commands/DriveForInches.h"
#include "Commands/TurnTo.h"
#include "Commands/DriveForInches.h"
#include "Commands/TurnTo.h"
#include "Commands/RaiseElevator.h"
#include "Commands/DriveForInches.h"
#include "Commands/OpenGrabber.h"
#include "Commands/DriveBackward.h"
#include "Commands/LowerElevator.h"
#include "Commands/TurnTo.h"
#include "Commands/DriveForInches.h"
#include "Commands/TurnTo.h"
#include "Commands/DriveForInches.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoPos2L2::AutoPos2L2() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
        AddSequential(new LowerElbow());
        AddSequential(new DriveForInches(48));
        AddSequential(new TurnTo(270));
        AddSequential(new DriveForInches(60));
        AddSequential(new TurnTo(0));
        AddSequential(new RaiseElevator());
        AddSequential(new DriveForInches(41));
        AddSequential(new OpenGrabber());
        AddSequential(new DriveBackward(41));
        AddSequential(new LowerElevator());
        AddSequential(new TurnTo(270));
        AddSequential(new DriveForInches(0));
        AddSequential(new TurnTo(0));
        AddSequential(new DriveForInches(48));
              // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
