// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "StopElevator.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

StopElevator::StopElevator(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void StopElevator::Initialize() {
SetTimeout(.01);
}

// Called repeatedly when this Command is scheduled to run
void StopElevator::Execute() {
	Robot::elBrake->BrakeOn();
Robot::elevator->ElevatorStop();
}

// Make this return true when this Command no longer needs to run execute()
bool StopElevator::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void StopElevator::End() {
	Robot::elBrake->BrakeOn();
Robot::elevator->ElevatorStop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void StopElevator::Interrupted() {
End();
}
