// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

#include "Commands/AutonomousCommand.h"
#include "Commands/AutoRoutine1.h"
#include "Commands/AutoPos1LL.h"
#include "Commands/AutoPos1RL.h"
#include "Commands/AutoPos1RR.h"
#include "Commands/AutoPos2L2.h"
#include "Commands/AutoPos2R2.h"
#include "Subsystems/Climber.h"
#include "Subsystems/DriveBase.h"
#include "Subsystems/ElBrake.h"
#include "Subsystems/Elbow.h"
#include "Subsystems/Elevator.h"
#include "Subsystems/Grabber.h"
#include "Subsystems/Shifter.h"


#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	frc::SendableChooser<frc::Command*> chooser;
	static std::shared_ptr<DriveBase> driveBase;
	static std::shared_ptr<Elevator> elevator;
	static std::shared_ptr<Elbow> elbow;
	static std::shared_ptr<Grabber> grabber;
	static std::shared_ptr<Shifter> shifter;
	static std::shared_ptr<Climber> climber;
	static std::shared_ptr<ElBrake> elBrake;

    void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
};
#endif
